-- DeepL Free translations of existing public dish names, requested by the owner.
-- Machine labels only; concurrent manual confirmations and source edits take precedence.
UPDATE dishes SET machine_name_en='Breaded fish fillet with potato wedges and green vegetables',machine_name_en_source='裹粉鱼排配薯角和绿色蔬菜' WHERE id='60731e59-7e96-45b6-824a-c80ee1b72cc2' AND coalesce(nullif(canonical_name_zh,''),original_description)='裹粉鱼排配薯角和绿色蔬菜' AND canonical_name_en IS NULL AND merged_into_dish_id IS NULL;
UPDATE dishes SET machine_name_en='Chocolate pudding',machine_name_en_source='巧克力布丁' WHERE id='6442f980-c674-43d4-a56d-eb174a474821' AND coalesce(nullif(canonical_name_zh,''),original_description)='巧克力布丁' AND canonical_name_en IS NULL AND merged_into_dish_id IS NULL;
UPDATE dishes SET machine_name_en='Potato salad',machine_name_en_source='土豆沙拉' WHERE id='2e1f6b18-f013-47f0-b0e9-017ba743d10f' AND coalesce(nullif(canonical_name_zh,''),original_description)='土豆沙拉' AND canonical_name_en IS NULL AND merged_into_dish_id IS NULL;
UPDATE dishes SET machine_name_en='Pasta, Beans and Stuffed Cutlet',machine_name_en_source='意面、豆子和夹心肉排' WHERE id='3dc63a37-5ad5-47f4-9b2a-b3ea00ca147c' AND coalesce(nullif(canonical_name_zh,''),original_description)='意面、豆子和夹心肉排' AND canonical_name_en IS NULL AND merged_into_dish_id IS NULL;
UPDATE dishes SET machine_name_en='Strawberry Yoghurt',machine_name_en_source='草莓酸奶' WHERE id='4cd3e95d-2ae4-4705-9cb6-95efe92367f2' AND coalesce(nullif(canonical_name_zh,''),original_description)='草莓酸奶' AND canonical_name_en IS NULL AND merged_into_dish_id IS NULL;
UPDATE dishes SET machine_name_en='Pudding',machine_name_en_source='布丁' WHERE id='4f3ab0cb-83c7-49ef-9dad-e033628b2a69' AND coalesce(nullif(canonical_name_zh,''),original_description)='布丁' AND canonical_name_en IS NULL AND merged_into_dish_id IS NULL;
UPDATE dishes SET machine_name_en='Lightning Profiteroles',machine_name_en_source='闪电泡芙' WHERE id='a29482cd-1995-450e-a69d-4b86ba460428' AND coalesce(nullif(canonical_name_zh,''),original_description)='闪电泡芙' AND canonical_name_en IS NULL AND merged_into_dish_id IS NULL;
UPDATE dishes SET machine_name_en='Chocolate sauce pancake',machine_name_en_source='巧克力酱pancake' WHERE id='0139a21b-b3a6-4d37-88ff-1ac21f103d74' AND coalesce(nullif(canonical_name_zh,''),original_description)='巧克力酱pancake' AND canonical_name_en IS NULL AND merged_into_dish_id IS NULL;
UPDATE dishes SET machine_name_en='Fish fillet, fried potato chunks and stir-fried vegetables',machine_name_en_source='鱼排、炸土豆块和炒蔬菜' WHERE id='04093568-d36e-40ff-8381-6f7abeb3788a' AND coalesce(nullif(canonical_name_zh,''),original_description)='鱼排、炸土豆块和炒蔬菜' AND canonical_name_en IS NULL AND merged_into_dish_id IS NULL;
UPDATE dishes SET machine_name_en='Eggs',machine_name_en_source='鸡蛋' WHERE id='634e7843-7e55-46a5-a427-729eaf5667e0' AND coalesce(nullif(canonical_name_zh,''),original_description)='鸡蛋' AND canonical_name_en IS NULL AND merged_into_dish_id IS NULL;
UPDATE dishes SET machine_name_en='Chocolate mousse',machine_name_en_source='巧克力慕斯' WHERE id='7d8d3ec3-0adf-474b-aa54-6a3d76a84a56' AND coalesce(nullif(canonical_name_zh,''),original_description)='巧克力慕斯' AND canonical_name_en IS NULL AND merged_into_dish_id IS NULL;
UPDATE dishes SET machine_name_en='Bread and cheese',machine_name_en_source='面包和奶酪' WHERE id='ab62ede7-df52-41e7-985e-75cb83a392e1' AND coalesce(nullif(canonical_name_zh,''),original_description)='面包和奶酪' AND canonical_name_en IS NULL AND merged_into_dish_id IS NULL;
UPDATE dishes SET machine_name_en='Diced Mixed Salad',machine_name_en_source='切丁混合沙拉' WHERE id='2845a9e6-5811-4c6d-bcb3-30420dccf5fd' AND coalesce(nullif(canonical_name_zh,''),original_description)='切丁混合沙拉' AND canonical_name_en IS NULL AND merged_into_dish_id IS NULL;
UPDATE dishes SET machine_name_en='Sausage, mixed vegetables, sauce and millet',machine_name_en_source='香肠、混合蔬菜、酱汁和小米' WHERE id='8f8cae63-a832-4f6f-8708-4fd91a6c4502' AND coalesce(nullif(canonical_name_zh,''),original_description)='香肠、混合蔬菜、酱汁和小米' AND canonical_name_en IS NULL AND merged_into_dish_id IS NULL;
UPDATE dishes SET machine_name_en='Yellow Peach',machine_name_en_source='黄桃' WHERE id='b5ce4b74-d69c-4196-a17c-6ff99c59011e' AND coalesce(nullif(canonical_name_zh,''),original_description)='黄桃' AND canonical_name_en IS NULL AND merged_into_dish_id IS NULL;
UPDATE dishes SET machine_name_en='Sausage with lentils and vegetables',machine_name_en_source='香肠配扁豆和蔬菜' WHERE id='f77b7560-3a4d-441f-961c-e4cc90bac49d' AND coalesce(nullif(canonical_name_zh,''),original_description)='香肠配扁豆和蔬菜' AND canonical_name_en IS NULL AND merged_into_dish_id IS NULL;
UPDATE dishes SET machine_name_en='Fresh shiitake mushrooms 🍄 and tomatoes 🍅',machine_name_en_source='生香菇🍄和西红柿🍅' WHERE id='d3affc90-2b48-4a64-a683-4b76d1688826' AND coalesce(nullif(canonical_name_zh,''),original_description)='生香菇🍄和西红柿🍅' AND canonical_name_en IS NULL AND merged_into_dish_id IS NULL;
